name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build . -t dkpk-hadoop:latest

      - name: Run
        run: docker run --rm --name dkpk-hadoop hdfs namenode -format
