name: Pull & Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull the image
        run: docker build . -t dkpk-hadoop:latest
        
      - name: List containers
        run: docker ps

      - name: Run
        run: docker run dkpk-hadoop -t hdfs namenode -format
