name: Pull & Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull the image
        run: docker pull sequenceiq/hadoop-docker:2.7.1
        
      - name: List containers
        run: docker ps
        
      - name: Run container
        run: docker run -t sequenceiq/hadoop-docker:2.7.1 /etc/bootstrap.sh hadoop fs -ls

